# Generated by Django 4.2.1 on 2023-07-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_range', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('oc_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe', models.CharField(blank=True, max_length=20, null=True)),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_age', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('p_address', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_OtherCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdata', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('othercharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.othercharges')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_table')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_LAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_table')),
            ],
        ),
        migrations.CreateModel(
            name='LAB_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_report_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('P_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_lab')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='labcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.labcategory'),
        ),
    ]
