# Generated by Django 4.2.1 on 2023-07-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_othercharges',
            old_name='billdata',
            new_name='billdate',
        ),
    ]
