# Generated by Django 4.2.1 on 2023-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_table',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
