# Generated by Django 4.2.1 on 2023-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_alter_patient_table_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_table',
            old_name='created_at',
            new_name='admission_date',
        ),
        migrations.RenameField(
            model_name='patient_table',
            old_name='updated_at',
            new_name='discharge_date',
        ),
        migrations.AddField(
            model_name='patient_table',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient_table',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
