# Generated by Django 4.2.1 on 2023-07-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_remove_patient_lab_lab_patient_lab_labcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_lab',
            name='labCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.labcategory'),
        ),
    ]
