# Generated by Django 4.2.1 on 2023-07-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_rename_created_at_patient_table_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_table',
            name='symptoms',
        ),
    ]
