# Generated by Django 4.2.1 on 2023-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_remove_patient_table_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_table',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
