# Generated by Django 4.2.1 on 2023-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0005_patient_table_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_table',
            name='oe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
