# Generated by Django 4.2.1 on 2023-07-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0006_patient_table_oe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_price', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_table')),
            ],
        ),
    ]
