# Generated by Django 4.2.1 on 2023-07-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0008_remove_lab_patient_patient_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_lab',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='patient_lab',
            name='lab_price',
        ),
        migrations.AddField(
            model_name='patient_lab',
            name='lab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HMS.lab'),
            preserve_default=False,
        ),
    ]
