# Generated by Django 4.2.1 on 2023-07-15 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0009_remove_patient_lab_lab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_lab',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
