# Generated by Django 4.2.1 on 2023-07-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0010_patient_lab_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_lab',
            name='lab',
        ),
        migrations.AddField(
            model_name='patient_lab',
            name='labs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
