# Generated by Django 4.2.1 on 2023-07-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0011_remove_patient_lab_lab_patient_lab_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='ref_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='LAB_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_report_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('P_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_lab')),
            ],
        ),
    ]
