# Generated by Django 4.2.1 on 2023-07-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0012_lab_ref_range_lab_units_lab_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Patient_OtherCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othercharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.othercharges')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.patient_table')),
            ],
        ),
    ]
