# Generated by Django 4.2.1 on 2023-07-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0013_othercharges_lab_category_lab_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercharges',
            old_name='lab_name',
            new_name='oc_name',
        ),
        migrations.RenameField(
            model_name='othercharges',
            old_name='lab_price',
            new_name='oc_price',
        ),
    ]
