# Generated by Django 4.2.1 on 2023-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0014_rename_lab_name_othercharges_oc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_othercharges',
            name='billdata',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-23 10:12:02'),
            preserve_default=False,
        ),
    ]
