# Generated by Django 4.2.1 on 2023-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0015_patient_othercharges_billdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_othercharges',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient_othercharges',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
